# Generated by Django 5.2.17 on 2026-09-06 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_queue_queueentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_id', models.CharField(max_length=30, unique=True)),
                ('priority', models.CharField(blank=True, choices=[('P1', 'Critical'), ('P2', 'Urgent'), ('P3', 'Lower Urgency')], max_length=2, null=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('TRIAGED', 'Triaged'), ('WAITING', 'Waiting'), ('IN_TREATMENT', 'In Treatment'), ('COMPLETED', 'Completed'), ('TRANSFERRED', 'Transferred')], default='REGISTERED', max_length=20)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_cases', to='core.hospital')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_cases', to='core.patient')),
            ],
        ),
    ]
