# Generated by Django 5.2.17 on 2026-09-06 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emergencycase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('bed_type', models.CharField(choices=[('GENERAL', 'General'), ('SEMI_PRIVATE', 'Semi Private'), ('PRIVATE', 'Private'), ('ICU', 'ICU'), ('EMERGENCY', 'Emergency')], max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('OCCUPIED', 'Occupied'), ('CLEANING', 'Cleaning'), ('MAINTENANCE', 'Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='core.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='core.hospital')),
            ],
        ),
    ]
