# Generated by Django 5.2.17 on 2026-09-06 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_bed_type', models.CharField(choices=[('GENERAL', 'General'), ('SEMI_PRIVATE', 'Semi Private'), ('PRIVATE', 'Private'), ('ICU', 'ICU'), ('EMERGENCY', 'Emergency')], max_length=20)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('URGENT', 'Urgent'), ('NORMAL', 'Normal')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('BED_RESERVED', 'Bed Reserved'), ('ADMITTED', 'Admitted'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_queue_entries', to='core.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_queue', to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_queue_entries', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='BedReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expected_arrival', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('CONVERTED_TO_OCCUPIED', 'Converted to Occupied')], default='ACTIVE', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_reservations', to='core.patient')),
            ],
        ),
    ]
